# Your workflow name.
name: Deploy to Render

# Run workflow on every push to the main branch.
on:
  push:
    branches: [main]

# Your workflows jobs.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check-out your repository.
      - name: Checkout
        uses: actions/checkout@v2

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build the project
      - name: Build project
        run: npm run build

      ### ⬇ IMPORTANT PART ⬇ ###

      - name: Deploy to Render # Your custom step name
        uses: render-examples/github-deploy-action@v1 # GitHub action name (leave it as it is).
        with:
          # Below you must provide variables for your Render app.

          # Render Service ID
          email: ${{ secrets.RENDER_EMAIL }}
          
          # Render API Key
          api-key: ${{ secrets.RENDER_API_KEY }}

          # (Optional, default: "web")
          # Select the service name or type for which you want the build to be deployed.
          # By default, this argument is set to "web".
          service-type: web
          
      ### ⬆ IMPORTANT PART ⬆ ###

